version: '2.1'
services:
    message-server:
        container_name: message-service
        build:
            context: ../../message-service/message-service
            dockerfile: Dockerfile
        image: message-service:0.0.1
        depends_on:
            - eureka-server
        links:
            - eureka-server
        environment:
            - POSTGRES_APP_HOST=postgresdb
            - POSTGRES_APP_PORT=5432
            - POSTGRES_APP_USERNAME=postgres
            - POSTGRES_APP_PASSWORD=root-postgres
            - EUREKA_APP_HOST=eureka-server
            - EUREKA_APP_PORT=6060
            - KAFKA_SERVER_NAME=kafka
            - KAFKA_SERVER_PORT=9092
            - KAFKA_GROUP_ID=userGroup
        ports:
            - 17070:7070
        networks:
            - backend
            - kafka-server_kafka-network
            - postgresdb-server_postgresdb-network
            - nginx-server_nginx-network

    user-server:
        container_name: user-service
        depends_on:
            - eureka-server
        links:
            - eureka-server
        environment:
            - POSTGRES_APP_HOST=postgresdb
            - POSTGRES_APP_PORT=5432
            - POSTGRES_APP_USERNAME=postgres
            - POSTGRES_APP_PASSWORD=root-postgres
            - EUREKA_APP_HOST=eureka-server
            - EUREKA_APP_PORT=6060
            - KAFKA_SERVER_NAME=kafka
            - KAFKA_SERVER_PORT=9092
        build:
            context: ../../user-service/user-service
            dockerfile: Dockerfile
        image: user-service:0.0.1
        ports:
            - 17080:7080
        networks:
            - backend
            - kafka-server_kafka-network
            - postgresdb-server_postgresdb-network
            - nginx-server_nginx-network

    document-server:
        container_name: document-service
        image: document-service:0.0.1
        build:
            context: ../../document-service/document-service
        ports:
            - 17090:7090
        depends_on:
            - eureka-server
        links:
            - eureka-server
        environment:
            - POSTGRES_APP_HOST=postgresdb
            - POSTGRES_APP_PORT=5432
            - POSTGRES_APP_USERNAME=postgres
            - POSTGRES_APP_PASSWORD=root-postgres
            - EUREKA_APP_HOST=eureka-server
            - EUREKA_APP_PORT=6060
        networks:
            - backend
            - postgresdb-server_postgresdb-network
            - nginx-server_nginx-network
        volumes:
            - documents:/home/storage

    gateway-server:
        image: gateway-service:0.0.1
        container_name: gateway-service
        build:
            context: ../../gateway-service/gateway-service
            dockerfile: Dockerfile
        ports:
            - 15050:5050
        depends_on:
            - eureka-server
        links:
            - eureka-server
        environment:
            - EUREKA_APP_HOST=eureka-server
            - EUREKA_APP_PORT=6060
        networks:
            - backend
            - nginx-server_nginx-network

    eureka-server:
        image: eureka-server:0.0.1
        container_name: eureka-server
        build:
            context: ../../eureka-server/eureka-server
            dockerfile: Dockerfile
        environment:
            - EUREKA_APP_HOST=eureka-server
        ports:
            - 6060:6060
        networks:
            - backend
            - nginx-server_nginx-network

networks:
     backend:
        driver: bridge
     kafka-server_kafka-network:
        driver: bridge
        external: true
     postgresdb-server_postgresdb-network:
        driver: bridge
        external: true
     nginx-server_nginx-network:
        driver: bridge
        external: true
volumes:
    documents:
        driver: local